#!/usr/bin/env perl

use strict;
use warnings;
use FindBin qw($RealBin);
use lib "$RealBin/lib";
use MorseEncoder;

die "Usage: $0 <input_file>\n" unless @ARGV == 1;

open my $fh, '<', $ARGV[0] or die "Cannot open '$ARGV[0]': $!\n";

while (my $line = <$fh>) {
    chomp $line;
    next if $line =~ /^\s*$/;
    print MorseEncoder::encode_line($line), "\n";
}

close $fh;
