import type { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
  panel: { padding: "28px 32px" },
  title: {
    fontSize: "22px",
    fontWeight: 700,
    marginBottom: "6px",
    color: "#f1f5f9",
    letterSpacing: "-0.01em",
  },
  desc: {
    color: "#94a3b8",
    marginBottom: "20px",
    fontSize: "14px",
    lineHeight: 1.6,
  },
  grid: { display: "flex", flexDirection: "column", gap: "24px" },
  section: {
    padding: "18px",
    background: "#1e293b",
    borderRadius: "8px",
    border: "1px solid #334155",
  },
  sectionTitle: {
    fontSize: "15px",
    fontWeight: 600,
    marginBottom: "14px",
    color: "#f1f5f9",
    letterSpacing: "-0.01em",
  },
  form: {
    display: "flex",
    gap: "8px",
    flexWrap: "wrap",
    alignItems: "center",
  },
  input: {
    padding: "8px 12px",
    background: "#0f172a",
    border: "1px solid #334155",
    borderRadius: "6px",
    color: "#e2e8f0",
    fontSize: "13px",
  },
  select: {
    padding: "8px 12px",
    background: "#0f172a",
    border: "1px solid #334155",
    borderRadius: "6px",
    color: "#e2e8f0",
    fontSize: "13px",
  },
  btn: {
    padding: "8px 16px",
    background: "#2563eb",
    color: "#fff",
    border: "none",
    borderRadius: "6px",
    cursor: "pointer",
    fontSize: "13px",
    fontWeight: 600,
  },
  btnSmall: {
    padding: "4px 10px",
    background: "transparent",
    color: "#94a3b8",
    border: "1px solid #475569",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "12px",
    fontWeight: 500,
  },
  btnDanger: {
    padding: "8px 16px",
    background: "#b91c1c",
    color: "#fff",
    border: "none",
    borderRadius: "6px",
    cursor: "pointer",
    fontSize: "13px",
    fontWeight: 600,
  },
  btnDangerSmall: {
    padding: "4px 10px",
    background: "transparent",
    color: "#f87171",
    border: "1px solid #7f1d1d",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "12px",
    fontWeight: 500,
  },
  btnSuccessSmall: {
    padding: "4px 10px",
    background: "#15803d",
    color: "#fff",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "12px",
    fontWeight: 600,
  },
  btnWarningSmall: {
    padding: "4px 10px",
    background: "transparent",
    color: "#fbbf24",
    border: "1px solid #92400e",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "12px",
    fontWeight: 500,
  },
  btnCancelSmall: {
    padding: "4px 10px",
    background: "transparent",
    color: "#94a3b8",
    border: "1px solid #475569",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "12px",
    fontWeight: 500,
  },
  success: {
    marginTop: "8px",
    padding: "8px 12px",
    background: "#064e3b",
    borderRadius: "6px",
    color: "#6ee7b7",
    fontSize: "13px",
  },
  error: {
    marginTop: "8px",
    padding: "8px 12px",
    background: "#7f1d1d",
    borderRadius: "6px",
    color: "#fca5a5",
    fontSize: "13px",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    marginTop: "14px",
    fontSize: "13px",
  },
  th: {
    textAlign: "left",
    padding: "10px 10px 8px",
    borderBottom: "1px solid #475569",
    color: "#64748b",
    fontSize: "11px",
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: "0.05em",
  },
  td: {
    padding: "10px 10px",
    borderBottom: "1px solid rgba(51, 65, 85, 0.4)",
    color: "#cbd5e1",
    verticalAlign: "middle",
  },
  editInput: {
    padding: "6px 10px",
    background: "#0f172a",
    border: "1px solid #38bdf8",
    borderRadius: "4px",
    color: "#e2e8f0",
    fontSize: "13px",
    width: "100%",
  },
  filterRow: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    marginTop: "12px",
  },
  filterInput: {
    padding: "6px 10px",
    background: "#0f172a",
    border: "1px solid #334155",
    borderRadius: "6px",
    color: "#e2e8f0",
    fontSize: "13px",
    width: "220px",
  },
  filterLabel: {
    fontSize: "12px",
    color: "#64748b",
  },
  actions: {
    display: "flex",
    gap: "6px",
    flexWrap: "wrap",
  },
  statusBadge: {
    display: "inline-block",
    padding: "2px 8px",
    borderRadius: "10px",
    fontSize: "11px",
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: "0.03em",
  },
  emptyRow: {
    padding: "24px 10px",
    color: "#475569",
    fontStyle: "italic",
    textAlign: "center",
  },
  rowError: {
    color: "#fca5a5",
    fontSize: "12px",
    marginTop: "4px",
  },
};
