import type { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
  panel: { padding: "24px" },
  title: { fontSize: "24px", marginBottom: "8px", color: "#f1f5f9" },
  desc: { color: "#94a3b8", marginBottom: "16px", fontSize: "14px" },
  grid: { display: "flex", flexDirection: "column", gap: "24px" },
  section: {
    padding: "16px",
    background: "#1e293b",
    borderRadius: "8px",
    border: "1px solid #334155",
  },
  sectionTitle: {
    fontSize: "16px",
    marginBottom: "12px",
    color: "#38bdf8",
  },
  form: {
    display: "flex",
    gap: "8px",
    flexWrap: "wrap",
    alignItems: "center",
  },
  input: {
    padding: "8px 12px",
    background: "#0f172a",
    border: "1px solid #334155",
    borderRadius: "6px",
    color: "#e2e8f0",
    fontSize: "14px",
  },
  select: {
    padding: "8px 12px",
    background: "#0f172a",
    border: "1px solid #334155",
    borderRadius: "6px",
    color: "#e2e8f0",
    fontSize: "14px",
  },
  btn: {
    padding: "8px 16px",
    background: "#2563eb",
    color: "#fff",
    border: "none",
    borderRadius: "6px",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: 600,
  },
  btnSmall: {
    padding: "4px 10px",
    background: "#2563eb",
    color: "#fff",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "12px",
    fontWeight: 600,
  },
  btnDanger: {
    padding: "8px 16px",
    background: "#b91c1c",
    color: "#fff",
    border: "none",
    borderRadius: "6px",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: 600,
  },
  btnDangerSmall: {
    padding: "4px 10px",
    background: "#b91c1c",
    color: "#fff",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "12px",
    fontWeight: 600,
  },
  btnSuccessSmall: {
    padding: "4px 10px",
    background: "#15803d",
    color: "#fff",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "12px",
    fontWeight: 600,
  },
  btnWarningSmall: {
    padding: "4px 10px",
    background: "#d97706",
    color: "#fff",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "12px",
    fontWeight: 600,
  },
  btnCancelSmall: {
    padding: "4px 10px",
    background: "#475569",
    color: "#fff",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "12px",
    fontWeight: 600,
  },
  success: {
    marginTop: "8px",
    padding: "8px 12px",
    background: "#064e3b",
    borderRadius: "6px",
    color: "#6ee7b7",
    fontSize: "13px",
  },
  error: {
    marginTop: "8px",
    padding: "8px 12px",
    background: "#7f1d1d",
    borderRadius: "6px",
    color: "#fca5a5",
    fontSize: "13px",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    marginTop: "12px",
    fontSize: "13px",
  },
  th: {
    textAlign: "left",
    padding: "8px",
    borderBottom: "2px solid #334155",
    color: "#94a3b8",
    fontSize: "12px",
    fontWeight: 600,
    textTransform: "uppercase",
  },
  td: {
    padding: "8px",
    borderBottom: "1px solid #334155",
    color: "#cbd5e1",
  },
  editInput: {
    padding: "4px 8px",
    background: "#0f172a",
    border: "1px solid #334155",
    borderRadius: "4px",
    color: "#e2e8f0",
    fontSize: "13px",
    width: "100%",
  },
  filterInput: {
    padding: "6px 10px",
    background: "#0f172a",
    border: "1px solid #334155",
    borderRadius: "6px",
    color: "#e2e8f0",
    fontSize: "13px",
    marginTop: "12px",
    width: "250px",
  },
  actions: {
    display: "flex",
    gap: "4px",
    flexWrap: "wrap",
  },
  statusBadge: {
    padding: "2px 8px",
    borderRadius: "4px",
    fontSize: "11px",
    fontWeight: 600,
    textTransform: "uppercase",
  },
  emptyRow: {
    padding: "16px 8px",
    color: "#64748b",
    fontStyle: "italic",
  },
};
